<?php
namespace Database\Seeders;

use App\Models\County;
use Illuminate\Database\Seeder;

class CountyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $counties = [
['name'=>'آبادان','province_id'=>13],
['name'=>'آباده','province_id'=>17],
['name'=>'آبدانان','province_id'=>6],
['name'=>'آبیک','province_id'=>18],
['name'=>'آذرشهر','province_id'=>1],
['name'=>'آرادان','province_id'=>15],
['name'=>'آران وبیدگل','province_id'=>4],
['name'=>'آزادشهر','province_id'=>24],
['name'=>'آستارا','province_id'=>25],
['name'=>'آستانه اشرفیه','province_id'=>25],
['name'=>'آشتیان','province_id'=>28],
['name'=>'آغاجاری','province_id'=>13],
['name'=>'آق قلا','province_id'=>24],
['name'=>'آمل','province_id'=>27],
['name'=>'آوج','province_id'=>18],
['name'=>'ابرکوه','province_id'=>31],
['name'=>'ابوموسی','province_id'=>29],
['name'=>'ابهر','province_id'=>14],
['name'=>'اراک','province_id'=>28],
['name'=>'اردبیل','province_id'=>3],
['name'=>'اردستان','province_id'=>4],
['name'=>'اردکان','province_id'=>31],
['name'=>'اردل','province_id'=>9],
['name'=>'ارزوییه','province_id'=>21],
['name'=>'ارسنجان','province_id'=>17],
['name'=>'ارومیه','province_id'=>2],
['name'=>'ازنا','province_id'=>26],
['name'=>'استهبان','province_id'=>17],
['name'=>'اسدآباد','province_id'=>30],
['name'=>'اسفراین','province_id'=>12],
['name'=>'اسکو','province_id'=>1],
['name'=>'اسلام آبادغرب','province_id'=>22],
['name'=>'اسلامشهر','province_id'=>8],
['name'=>'اشتهارد','province_id'=>5],
['name'=>'اشکذر','province_id'=>31],
['name'=>'اشنویه','province_id'=>2],
['name'=>'اصفهان','province_id'=>4],
['name'=>'اصلاندوز','province_id'=>3],
['name'=>'اقلید','province_id'=>17],
['name'=>'البرز','province_id'=>18],
['name'=>'الیگودرز','province_id'=>26],
['name'=>'املش','province_id'=>25],
['name'=>'امیدیه','province_id'=>13],
['name'=>'انار','province_id'=>21],
['name'=>'اندیکا','province_id'=>13],
['name'=>'اندیمشک','province_id'=>13],
['name'=>'اهر','province_id'=>1],
['name'=>'اهواز','province_id'=>13],
['name'=>'ایجرود','province_id'=>14],
['name'=>'ایذه','province_id'=>13],
['name'=>'ایرانشهر','province_id'=>16],
['name'=>'ایلام','province_id'=>6],
['name'=>'ایوان','province_id'=>6],
['name'=>'بابل','province_id'=>27],
['name'=>'بابلسر','province_id'=>27],
['name'=>'باخرز','province_id'=>11],
['name'=>'باشت','province_id'=>23],
['name'=>'باغ ملک','province_id'=>13],
['name'=>'بافت','province_id'=>21],
['name'=>'بافق','province_id'=>31],
['name'=>'بانه','province_id'=>20],
['name'=>'باوی','province_id'=>13],
['name'=>'بجستان','province_id'=>11],
['name'=>'بجنورد','province_id'=>12],
['name'=>'بدره','province_id'=>6],
['name'=>'برخوار','province_id'=>4],
['name'=>'بردسکن','province_id'=>11],
['name'=>'بردسیر','province_id'=>21],
['name'=>'بروجرد','province_id'=>26],
['name'=>'بروجن','province_id'=>9],
['name'=>'بستان آباد','province_id'=>1],
['name'=>'بستک','province_id'=>29],
['name'=>'بشاگرد','province_id'=>29],
['name'=>'بشرویه','province_id'=>10],
['name'=>'بم','province_id'=>21],
['name'=>'بمپور','province_id'=>16],
['name'=>'بن','province_id'=>9],
['name'=>'بناب','province_id'=>1],
['name'=>'بندرانزلی','province_id'=>25],
['name'=>'بندرعباس','province_id'=>29],
['name'=>'بندرگز','province_id'=>24],
['name'=>'بندرلنگه','province_id'=>29],
['name'=>'بندرماهشهر','province_id'=>13],
['name'=>'بو یین و میاندشت','province_id'=>4],
['name'=>'بوانات','province_id'=>17],
['name'=>'بویین زهرا','province_id'=>18],
['name'=>'بوشهر','province_id'=>7],
['name'=>'بوکان','province_id'=>2],
['name'=>'بویراحمد','province_id'=>23],
['name'=>'بهاباد','province_id'=>31],
['name'=>'بهار','province_id'=>30],
['name'=>'بهارستان','province_id'=>8],
['name'=>'بهبهان','province_id'=>13],
['name'=>'بهشهر','province_id'=>27],
['name'=>'بهمیی','province_id'=>23],
['name'=>'بیجار','province_id'=>20],
['name'=>'بیرجند','province_id'=>10],
['name'=>'بیله سوار','province_id'=>3],
['name'=>'بینالود','province_id'=>11],
['name'=>'پارس آباد','province_id'=>3],
['name'=>'پارسیان','province_id'=>29],
['name'=>'پاسارگاد','province_id'=>17],
['name'=>'پاکدشت','province_id'=>8],
['name'=>'پاوه','province_id'=>22],
['name'=>'پردیس','province_id'=>8],
['name'=>'پلدختر','province_id'=>26],
['name'=>'پلدشت','province_id'=>2],
['name'=>'پیرانشهر','province_id'=>2],
['name'=>'پیشوا','province_id'=>8],
['name'=>'تاکستان','province_id'=>18],
['name'=>'تایباد','province_id'=>11],
['name'=>'تبریز','province_id'=>1],
['name'=>'تربت جام','province_id'=>11],
['name'=>'تربت حیدریه','province_id'=>11],
['name'=>'ترکمن','province_id'=>24],
['name'=>'تفت','province_id'=>31],
['name'=>'تفرش','province_id'=>28],
['name'=>'تکاب','province_id'=>2],
['name'=>'تنکابن','province_id'=>27],
['name'=>'تنگستان','province_id'=>7],
['name'=>'تویسرکان','province_id'=>30],
['name'=>'تهران','province_id'=>8],
['name'=>'تیران وکرون','province_id'=>4],
['name'=>'ثلاث باباجانی','province_id'=>22],
['name'=>'جاجرم','province_id'=>12],
['name'=>'جاسک','province_id'=>29],
['name'=>'جغتای','province_id'=>11],
['name'=>'جلفا','province_id'=>1],
['name'=>'جم','province_id'=>7],
['name'=>'جوانرود','province_id'=>22],
['name'=>'جویبار','province_id'=>27],
['name'=>'جوین','province_id'=>11],
['name'=>'جهرم','province_id'=>17],
['name'=>'جیرفت','province_id'=>21],
['name'=>'چابهار','province_id'=>16],
['name'=>'چادگان','province_id'=>4],
['name'=>'چاراویماق','province_id'=>1],
['name'=>'چالدران','province_id'=>2],
['name'=>'چالوس','province_id'=>27],
['name'=>'چایپاره','province_id'=>2],
['name'=>'چرام','province_id'=>23],
['name'=>'چرداول','province_id'=>6],
['name'=>'چگنی','province_id'=>26],
['name'=>'چناران','province_id'=>11],
['name'=>'حاجی اباد','province_id'=>29],
['name'=>'حمیدیه','province_id'=>13],
['name'=>'خاتم','province_id'=>31],
['name'=>'خاش','province_id'=>16],
['name'=>'خانمیرزا','province_id'=>9],
['name'=>'خداآفرین','province_id'=>1],
['name'=>'خدابنده','province_id'=>14],
['name'=>'خرامه','province_id'=>17],
['name'=>'خرم آباد','province_id'=>26],
['name'=>'خرم بید','province_id'=>17],
['name'=>'خرمدره','province_id'=>14],
['name'=>'خرمشهر','province_id'=>13],
['name'=>'خلخال','province_id'=>3],
['name'=>'خلیل آباد','province_id'=>11],
['name'=>'خمیر','province_id'=>29],
['name'=>'خمین','province_id'=>28],
['name'=>'خمینی شهر','province_id'=>4],
['name'=>'خنج','province_id'=>17],
['name'=>'خنداب','province_id'=>28],
['name'=>'خواف','province_id'=>11],
['name'=>'خوانسار','province_id'=>4],
['name'=>'خوی','province_id'=>2],
['name'=>'خور و بیابانک','province_id'=>4],
['name'=>'خوسف','province_id'=>10],
['name'=>'خوشاب','province_id'=>11],
['name'=>'داراب','province_id'=>17],
['name'=>'دالاهو','province_id'=>22],
['name'=>'دامغان','province_id'=>15],
['name'=>'داورزن','province_id'=>11],
['name'=>'درگز','province_id'=>11],
['name'=>'درمیان','province_id'=>10],
['name'=>'دره شهر','province_id'=>6],
['name'=>'دزفول','province_id'=>13],
['name'=>'دشت آزادگان','province_id'=>13],
['name'=>'دشتستان','province_id'=>7],
['name'=>'دشتی','province_id'=>7],
['name'=>'دلفان','province_id'=>26],
['name'=>'دلگان','province_id'=>16],
['name'=>'دلیجان','province_id'=>28],
['name'=>'دماوند','province_id'=>8],
['name'=>'دنا','province_id'=>23],
['name'=>'دورود','province_id'=>26],
['name'=>'دهاقان','province_id'=>4],
['name'=>'دهگلان','province_id'=>20],
['name'=>'دهلران','province_id'=>6],
['name'=>'دیر','province_id'=>7],
['name'=>'دیلم','province_id'=>7],
['name'=>'دیواندره','province_id'=>20],
['name'=>'رابر','province_id'=>21],
['name'=>'راز و جرگلان','province_id'=>12],
['name'=>'رامسر','province_id'=>27],
['name'=>'رامشیر','province_id'=>13],
['name'=>'رامهرمز','province_id'=>13],
['name'=>'رامیان','province_id'=>24],
['name'=>'راور','province_id'=>21],
['name'=>'ری','province_id'=>8],
['name'=>'رباط کریم','province_id'=>8],
['name'=>'رزن','province_id'=>30],
['name'=>'رستم','province_id'=>17],
['name'=>'رشت','province_id'=>25],
['name'=>'رشتخوار','province_id'=>11],
['name'=>'رضوانشهر','province_id'=>25],
['name'=>'رفسنجان','province_id'=>21],
['name'=>'روانسر','province_id'=>22],
['name'=>'رودان','province_id'=>29],
['name'=>'رودبار','province_id'=>25],
['name'=>'رودبارجنوب','province_id'=>21],
['name'=>'رودسر','province_id'=>25],
['name'=>'رومشکان','province_id'=>26],
['name'=>'ریگان','province_id'=>21],
['name'=>'زابل','province_id'=>16],
['name'=>'زاوه','province_id'=>11],
['name'=>'زاهدان','province_id'=>16],
['name'=>'زرند','province_id'=>21],
['name'=>'زرندیه','province_id'=>28],
['name'=>'زرین دشت','province_id'=>17],
['name'=>'زنجان','province_id'=>14],
['name'=>'زهک','province_id'=>16],
['name'=>'زیرکوه','province_id'=>10],
['name'=>'ساری','province_id'=>27],
['name'=>'سامان','province_id'=>9],
['name'=>'ساوجبلاغ','province_id'=>5],
['name'=>'ساوه','province_id'=>28],
['name'=>'سبزوار','province_id'=>11],
['name'=>'سپیدان','province_id'=>17],
['name'=>'سراب','province_id'=>1],
['name'=>'سراوان','province_id'=>16],
['name'=>'سرایان','province_id'=>10],
['name'=>'سرباز','province_id'=>16],
['name'=>'سربیشه','province_id'=>10],
['name'=>'سرپل ذهاب','province_id'=>22],
['name'=>'سرخس','province_id'=>11],
['name'=>'سرخه','province_id'=>15],
['name'=>'سردشت','province_id'=>2],
['name'=>'سرعین','province_id'=>3],
['name'=>'سروآباد','province_id'=>20],
['name'=>'سروستان','province_id'=>17],
['name'=>'سقز','province_id'=>20],
['name'=>'سلسله','province_id'=>26],
['name'=>'سلطانیه','province_id'=>14],
['name'=>'سلماس','province_id'=>2],
['name'=>'سمنان','province_id'=>15],
['name'=>'سمیرم','province_id'=>4],
['name'=>'سنقر','province_id'=>22],
['name'=>'سنندج','province_id'=>20],
['name'=>'سوادکوه','province_id'=>27],
['name'=>'سوادکوه شمالی','province_id'=>27],
['name'=>'سیاهکل','province_id'=>25],
['name'=>'سیب و سوران','province_id'=>16],
['name'=>'سیرجان','province_id'=>21],
['name'=>'سیروان','province_id'=>6],
['name'=>'سیریک','province_id'=>29],
['name'=>'سیمرغ','province_id'=>27],
['name'=>'شادگان','province_id'=>13],
['name'=>'شازند','province_id'=>28],
['name'=>'شاهرود','province_id'=>15],
['name'=>'شاهین دژ','province_id'=>2],
['name'=>'شاهین شهرومیمه','province_id'=>4],
['name'=>'شبستر','province_id'=>1],
['name'=>'شفت','province_id'=>25],
['name'=>'شمیرانات','province_id'=>8],
['name'=>'شوش','province_id'=>13],
['name'=>'شوشتر','province_id'=>13],
['name'=>'شوط','province_id'=>2],
['name'=>'شهربابک','province_id'=>21],
['name'=>'شهرضا','province_id'=>4],
['name'=>'شهرکرد','province_id'=>9],
['name'=>'شهریار','province_id'=>8],
['name'=>'شیراز','province_id'=>17],
['name'=>'شیروان','province_id'=>12],
['name'=>'صالح آباد','province_id'=>11],
['name'=>'صحنه','province_id'=>22],
['name'=>'صومعه سرا','province_id'=>25],
['name'=>'طارم','province_id'=>14],
['name'=>'طالقان','province_id'=>5],
['name'=>'طبس','province_id'=>10],
['name'=>'طوالش','province_id'=>25],
['name'=>'عباس آباد','province_id'=>27],
['name'=>'عجب شیر','province_id'=>1],
['name'=>'عسلویه','province_id'=>7],
['name'=>'علی آباد','province_id'=>24],
['name'=>'عنبرآباد','province_id'=>21],
['name'=>'فارسان','province_id'=>9],
['name'=>'فاروج','province_id'=>12],
['name'=>'فاریاب','province_id'=>21],
['name'=>'فامنین','province_id'=>30],
['name'=>'فراشبند','province_id'=>17],
['name'=>'فراهان','province_id'=>28],
['name'=>'فردوس','province_id'=>10],
['name'=>'فردیس','province_id'=>5],
['name'=>'فریدن','province_id'=>4],
['name'=>'فریدونشهر','province_id'=>4],
['name'=>'فریدونکنار','province_id'=>27],
['name'=>'فریمان','province_id'=>11],
['name'=>'فسا','province_id'=>17],
['name'=>'فلاورجان','province_id'=>4],
['name'=>'فنوج','province_id'=>16],
['name'=>'فومن','province_id'=>25],
['name'=>'فهرج','province_id'=>21],
['name'=>'فیروزآباد','province_id'=>17],
['name'=>'فیروزکوه','province_id'=>8],
['name'=>'فیروزه','province_id'=>11],
['name'=>'قایم شهر','province_id'=>27],
['name'=>'قاینات','province_id'=>10],
['name'=>'قدس','province_id'=>8],
['name'=>'قرچک','province_id'=>8],
['name'=>'قروه','province_id'=>20],
['name'=>'قزوین','province_id'=>18],
['name'=>'قشم','province_id'=>29],
['name'=>'قصرشیرین','province_id'=>22],
['name'=>'قصرقند','province_id'=>16],
['name'=>'قلعه گنج','province_id'=>21],
['name'=>'قم','province_id'=>19],
['name'=>'قوچان','province_id'=>11],
['name'=>'قیروکارزین','province_id'=>17],
['name'=>'کارون','province_id'=>13],
['name'=>'کازرون','province_id'=>17],
['name'=>'کاشان','province_id'=>4],
['name'=>'کاشمر','province_id'=>11],
['name'=>'کامیاران','province_id'=>20],
['name'=>'کبودرآهنگ','province_id'=>30],
['name'=>'کرج','province_id'=>5],
['name'=>'کردکوی','province_id'=>24],
['name'=>'کرمان','province_id'=>21],
['name'=>'کرمانشاه','province_id'=>22],
['name'=>'کلات','province_id'=>11],
['name'=>'کلاردشت','province_id'=>27],
['name'=>'کلاله','province_id'=>24],
['name'=>'کلیبر','province_id'=>1],
['name'=>'کمیجان','province_id'=>28],
['name'=>'کنارک','province_id'=>16],
['name'=>'کنگان','province_id'=>7],
['name'=>'کنگاور','province_id'=>22],
['name'=>'کوار','province_id'=>17],
['name'=>'کوثر','province_id'=>3],
['name'=>'کوهبنان','province_id'=>21],
['name'=>'کوهدشت','province_id'=>26],
['name'=>'کوهرنگ','province_id'=>9],
['name'=>'کهگیلویه','province_id'=>23],
['name'=>'کهنوج','province_id'=>21],
['name'=>'کیار','province_id'=>9],
['name'=>'گالیکش','province_id'=>24],
['name'=>'گتوند','province_id'=>13],
['name'=>'گچساران','province_id'=>23],
['name'=>'گراش','province_id'=>17],
['name'=>'گرگان','province_id'=>24],
['name'=>'گرمسار','province_id'=>15],
['name'=>'گرمه','province_id'=>12],
['name'=>'گرمی','province_id'=>3],
['name'=>'گلپایگان','province_id'=>4],
['name'=>'گلوگاه','province_id'=>27],
['name'=>'گمیشان','province_id'=>24],
['name'=>'گناباد','province_id'=>11],
['name'=>'گناوه','province_id'=>7],
['name'=>'گنبدکاووس','province_id'=>24],
['name'=>'گیلانغرب','province_id'=>22],
['name'=>'لارستان','province_id'=>17],
['name'=>'لالی','province_id'=>13],
['name'=>'لامرد','province_id'=>17],
['name'=>'لاهیجان','province_id'=>25],
['name'=>'لردگان','province_id'=>9],
['name'=>'لنجان','province_id'=>4],
['name'=>'لنده','province_id'=>23],
['name'=>'لنگرود','province_id'=>25],
['name'=>'ماسال','province_id'=>25],
['name'=>'ماکو','province_id'=>2],
['name'=>'مانه وسملقان','province_id'=>12],
['name'=>'ماهنشان','province_id'=>14],
['name'=>'مبارکه','province_id'=>4],
['name'=>'محلات','province_id'=>28],
['name'=>'محمودآباد','province_id'=>27],
['name'=>'مراغه','province_id'=>1],
['name'=>'مراوه تپه','province_id'=>24],
['name'=>'مرند','province_id'=>1],
['name'=>'مرودشت','province_id'=>17],
['name'=>'مریوان','province_id'=>20],
['name'=>'مسجدسلیمان','province_id'=>13],
['name'=>'مشگین شهر','province_id'=>3],
['name'=>'مشهد','province_id'=>11],
['name'=>'ملارد','province_id'=>8],
['name'=>'ملایر','province_id'=>30],
['name'=>'ملکان','province_id'=>1],
['name'=>'ملکشاهی','province_id'=>6],
['name'=>'ممسنی','province_id'=>17],
['name'=>'منوجان','province_id'=>21],
['name'=>'مه ولات','province_id'=>11],
['name'=>'مهاباد','province_id'=>2],
['name'=>'مهدی شهر','province_id'=>15],
['name'=>'مهر','province_id'=>17],
['name'=>'مهران','province_id'=>6],
['name'=>'مهرستان','province_id'=>16],
['name'=>'مهریز','province_id'=>31],
['name'=>'میامی','province_id'=>15],
['name'=>'میاندوآب','province_id'=>2],
['name'=>'میاندورود','province_id'=>27],
['name'=>'میانه','province_id'=>1],
['name'=>'میبد','province_id'=>31],
['name'=>'میرجاوه','province_id'=>16],
['name'=>'میناب','province_id'=>29],
['name'=>'مینودشت','province_id'=>24],
['name'=>'نایین','province_id'=>4],
['name'=>'نجف آباد','province_id'=>4],
['name'=>'نرماشیر','province_id'=>21],
['name'=>'نطنز','province_id'=>4],
['name'=>'نظرآباد','province_id'=>5],
['name'=>'نقده','province_id'=>2],
['name'=>'نکا','province_id'=>27],
['name'=>'نمین','province_id'=>3],
['name'=>'نور','province_id'=>27],
['name'=>'نوشهر','province_id'=>27],
['name'=>'نهاوند','province_id'=>30],
['name'=>'نهبندان','province_id'=>10],
['name'=>'نی ریز','province_id'=>17],
['name'=>'نیر','province_id'=>3],
['name'=>'نیشابور','province_id'=>11],
['name'=>'نیک شهر','province_id'=>16],
['name'=>'نیمروز','province_id'=>16],
['name'=>'ورامین','province_id'=>8],
['name'=>'ورزقان','province_id'=>1],
['name'=>'هامون','province_id'=>16],
['name'=>'هرسین','province_id'=>22],
['name'=>'هریس','province_id'=>1],
['name'=>'هشترود','province_id'=>1],
['name'=>'هفتکل','province_id'=>13],
['name'=>'همدان','province_id'=>30],
['name'=>'هندیجان','province_id'=>13],
['name'=>'هوراند','province_id'=>1],
['name'=>'هویزه','province_id'=>13],
['name'=>'هیرمند','province_id'=>16],
['name'=>'یزد','province_id'=>31]
];

       County::insert($counties);
    }
}
